#!/bin/bash


COOKIEFILE="${COOKIEFILE:-/tmp/stubu.cookie}"

URL_API="http://localhost:8080/stubu/api"

alias _s_curl="curl -L -k -b \"${COOKIEFILE}\" -H'Accept:application/json' -H'Content-type:application/json' -s " ## service
alias _sl_curl="curl -L -k -c \"${COOKIEFILE}\" -H'Accept:application/json' -H'Content-type:application/json' -s " ## login

_OK=0
_NOK=1

sl_curl() {
    local method="${1:?HTTP method missing}"
    shift;
    local endpoint="${1:?Endpoint missing}"
    shift;

    local result=$(_sl_curl "${URL_API}${endpoint}" -w "\nstatus[${endpoint}]: %{http_code}" -X "${method}" "${@}");
    local status=$(echo "${result}" | tail -1);
    local code=$(echo "${status}" | sed -e 's/^.*: //g')

    echo "${result}" | sed -e 's/^status\[.*\]: [0-9]*$//g'
    echo "${status}" >&2

    { [[ ${code:-600} -ge 400 ]] || [[ ${code:-000} -lt 100 ]] ; } && return ${_NOK} || return ${_OK}
}

sb_curl() {
    local method="${1:?HTTP method missing}"
    shift;
    local endpoint="${1:?Endpoint missing}"
    shift;

    local result=$(_s_curl "${URL_API}${endpoint}" -w "\nstatus[${endpoint}]: %{http_code}" -X "${method}" "${@}");
    local status=$(echo "${result}" | tail -1);
    local code=$(echo "${status}" | sed -e 's/^.*: //g')

    echo "${result}" | sed -e 's/^status\[.*\]: [0-9]*$//g'
    echo "${status}" >&2

    { [[ ${code:-600} -ge 400 ]] || [[ ${code:-000} -lt 100 ]] ; } && return ${_NOK} || return ${_OK}
}

mkjsonarr() {
    local arr="[";
    local first=true
    for elem in "${@}" ; do
        [ -z "${elem}" ] && continue;

        [[ ${first} = false ]] && {
            arr="${arr},";
        } || {
            first=false
        }

        [[ "${elem}" =~ ^\{.*\}$ ]] && {
            arr="${arr}${elem}"
        } || {
            arr="${arr}\"${elem}\""
        }
    done;

    echo "${arr}]"
}


# Make an array of JSON objects.
# Objects are to contain a single key-value pair
# E.g.: mkjsonobjarr "username:andhop0402" "username:mickeythemouse"
mkjsonobjarr() {
    local arr="[";
    local first=true
    for elem in "${@}" ; do
        [ -z "${elem}" ] && continue;

        [[ ${first} = false ]] && {
            arr="${arr},";
        } || {
            first=false
        }

        arr="${arr}$(mkjsonobj "${elem}")"
    done;

    echo "${arr}]"
}


mkjsonobj() {
    local json="{";
    local first=true
    local key;
    local value;

    { [[ ${#@} -eq 1 ]] && [[ "${1}" =~ ^\{.*\}$ ]] ; } && {
        json=${1}
    } || {
        for elem in "${@}" ; do

            key="${elem%%:*}"
            value="${elem#*:}"
            [ -z "${value}" ] && {
                value="null";
            } || {
                { [[ "${value}" =~ ^\[.*\]$ ]] || [[ "${value}" =~ ^\{.*\}$ ]] ; } && {
                    :;
                } || {
                    value="\"${value}\"";
                }
            }

            key="\"${key}\"";

            [[ ${first} = false ]] && {
                key=",${key}"
            } || {
                first=false
            }
#            echo "Appending value: [${value}]" >&2

            json="${json}${key}:${value}"
        done;

        json="${json}}"
    }

    echo "${json}"
}

## optional value
optional() {
    local value=${1:--}
    local def=${2}

    { [ -z "${value}" ] || [ "${value}" = "-" ] ; } && {
        value=${def}
    }
    echo "${value}"
}

urlencode() {
  local string="${1}"
  local strlen=${#string}
  local encoded=""
  local pos c o

  for (( pos=0 ; pos<strlen ; pos++ )); do
     c=${string:$pos:1}
     case "$c" in
        [-_.~a-zA-Z0-9] ) o="${c}" ;;
        * )               printf -v o '%%%02x' "'$c"
     esac
     encoded+="${o}"
  done
  echo "${encoded}"    # You can either set a return variable (FASTER) 
  URLENCODED="${encoded}"   #+or echo the result (EASIER)... or both... :p

}

adjustTimestamp() {
    local timestamp=${1}

    [ -z "${timestamp}" ] && {
        echo "";
        return
    }

    while [[ ${#timestamp} -lt 13 ]] ; do
        timestamp="${timestamp}0";
    done;

    while [[ ${#timestamp} -gt 13 ]] ; do
        timestamp="${timestamp:0:-1}";
    done;

    echo "${timestamp}"
}


validateTimeUnit() {
    local unit=${1}

    [ -z "${unit}" ] && return ${_NOK}

    case ${unit} in
        "M") ;; ## months
        "d") ;; ## days
        "H") ;; ## hours
        "m") ;; ## minutes
        "s") ;; ## seconds
        *) return ${_NOK}
    esac;

    return ${_OK}
}
